export const CONTACT_PAGE = {
  CONTRACT: 1,
  ADDRESS_FOOTER: 2,
};

export const GLOBAL_STATUS = {
  INACTIVE: 0,
  ACTIVE: 1,
};

export const MASTER_DATA_NAME = {
  STATUS_ORDER:1,
  LEVEL_USER: 2,
  UNIT_PRODUCT: 3,
  CAPACITY_PRODUCT: 4,
  ROLE: 5,
  CONDITIONS_LEVEL:6,
  PERCENT_REFERRAL: 7,
}

export const CONTENT_PAGE = {
  INTRODUCE_PAGE: 1,
  INTRODUCE_PAGE_STORY: 2,
  INTRODUCE_PAGE_CUSTOMER: 3,
  SCHOOL_PAGE_OVERVIEW: 4,
  SCHOOL_PAGE_PROCESS: 5,
  POLICY_PAGE_GUIDE: 6,
  POLICY_PAGE_RETURN: 7,
  POLICY_PAGE_DELIVER: 8,
  POLICY_PAGE_SECURITY: 9,
};

export const IMAGE_TYPE = {
  SUB: 0,
  MAIN: 1
};


export const SLIDE_PAGE = {
  HOME_PAGE_MAIN_PC: 1,
  HOME_PAGE_MAIN_SMARTPHONE: 2,
  HOME_PAGE_ADVERTMENT: 3,
  SCHOOL_PAGE: 4
};

export const TOKEN_API = {
  GIAO_HANG_TIET_KIEM: "A947Fb917eF4D78C188DAa2CdBa2354a0f6FF570",
  GIAO_HANG_NHANH: "92565b32-00d1-11ed-8636-7617f3863de9",
};

