export const CONTACT_PAGE = {
  CONTRACT: 1,
  ADDRESS_FOOTER: 2,
};

export const GLOBAL_STATUS = {
  INACTIVE: 0,
  ACTIVE: 1,
};

export const CONTENT_PAGE = {
  INTRODUCE_PAGE: 1,
  INTRODUCE_PAGE_STORY: 2,
  INTRODUCE_PAGE_CUSTOMER: 3,
  SCHOOL_PAGE_OVERVIEW: 4,
  SCHOOL_PAGE_PROCESS: 5,
  POLICY_PAGE_GUIDE: 6,
  POLICY_PAGE_RETURN: 7,
  POLICY_PAGE_DELIVER: 8,
  POLICY_PAGE_SECURITY: 9,
};


export const SLIDE_PAGE = {
  HOME_PAGE_MAIN_PC: 1,
  HOME_PAGE_MAIN_SMARTPHONE: 2,
  HOME_PAGE_ADVERTMENT: 3,
  SCHOOL_PAGE: 4
};

