import Head from "next/head";
import Image from "next/image";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Scrollbar, A11y, EffectCube } from "swiper";
import "swiper/swiper-bundle.min.css";
import "swiper/css";
import feed1 from "../public/feed1.jpg";
import Slider from "react-slick";
import { GrPrevious, GrNext } from "react-icons/gr";

import {
  Button,
  CartSlide,
  Footer,
  ItemSlide,
  Menu,
  SEO,
  Title,
} from "@/components";
import logosheshe from "../public/logosheshe.png";
import { useRouter } from "next/router";
import axios from "axios";
import { getRandomJoke } from "@/apis/axiosClient";
import configPageApis from "@/apis/configPageApis";
import { CONTENT_PAGE, GLOBAL_STATUS, SLIDE_PAGE } from "@/constants";
import { useEffect, useState } from "react";

const OUTSTANDING_PRODUCTS = 1;
const fetcher = (...args) => fetch(...args).then((res) => res.json());
export default function Home({ data }) {
  console.log(data);
  function addProductJsonLd() {
    return {
      __html: `{
      "@context": "http://localhost:3000/",
      "@type": "Product",
      "name": "CÔNG TY CỔ PHẦN TẬP ĐOÀN SHESHI",
      "image": [${product?.map((item) =>
        console.log(item?.productCategory?.image)
      )}],
      "description": "Sleeker than ACME's Classic Anvil, the Executive Anvil is perfect for the business traveler looking for something to drop from a height.",
      "sku": "0446310786",
      "mpn": "925872",
      "brand": {
        "@type": "Brand",
        "name": "ACME"
      },
      "review": {
        "@type": "Review",
        "reviewRating": {
          "@type": "Rating",
          "ratingValue": "4",
          "bestRating": "5"
        },
        "author": {
          "@type": "Person",
          "name": "Fred Benson"
        }
      },
      "aggregateRating": {
        "@type": "AggregateRating",
        "ratingValue": "4.4",
        "reviewCount": "89"
      },
      "offers": {
        "@type": "Offer",
        "url": "https://example.com/anvil",
        "priceCurrency": "USD",
        "price": "119.99",
        "priceValidUntil": "2020-11-20",
        "itemCondition": "https://schema.org/UsedCondition",
        "availability": "https://schema.org/InStock"
      }
    }
  `,
    };
  }

  const [product, setProduct] = useState();
  const [productNew, setProductNew] = useState();

  const getOutstandingProducts = async () => {
    const params = {
      size: 5,
      outstanding: OUTSTANDING_PRODUCTS,
      getMainImage: true,
      status: GLOBAL_STATUS.ACTIVE,
    };
    // console.log(params)

    const result = await axios.get("http://localhost:3001/api/product", {
      params,
    });
    console.log(result.data);
    setProduct(result.data.rows);
  };
  const getProductRelated = async () => {
    const params = {
      size: 5,
      getMainImage: true,
      status: GLOBAL_STATUS.ACTIVE,
    };

    // const return1 =
    const result = await axios.get("http://localhost:3001/api/product", {
      params,
    });
    setProductNew(result.data.rows);
  };

  useEffect(() => {
    getOutstandingProducts(), getProductRelated();
  }, []);
  console.log("product", product);

  const SlickArrowLeft = ({ currentSlide, slideCount, ...props }) => (
    <div {...props}>
      <GrPrevious></GrPrevious>
    </div>
  );
  const SlickArrowRight = ({ currentSlide, slideCount, ...props }) => (
    <div {...props}>
      <GrNext></GrNext>
    </div>
  );
  const settings = {
    dots: true,
    infinite: false,
    speed: 500,
    slidesToShow: 4,
    slidesToScroll: 4,
    prevArrow: <SlickArrowLeft />,
    nextArrow: <SlickArrowRight />,
    responsive: [
      {
        breakpoint: 1198,
        settings: {
          infinite: true,
          slidesToShow: 2,
          slidesToScroll: 2,
          rows: 1,
          dots: false,
        },
      },
      {
        breakpoint: 576,
        settings: {
          infinite: true,
          slidesToShow: 1,
          slidesToScroll: 1,
          rows: 1,
          dots: false,
        },
      },
    ],
  };

  return (
    <>
      <Head>
        <meta charset="UTF-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logosheshe.png" />
        <title>CÔNG TY CỔ PHẦN TẬP ĐOÀN SHESHI</title>
        {product?.map((item) => (
          <meta
            name="description"
            content={item?.description?.replace(/(<([^>]+)>)/gi, "")}
            key="desc"
          />
        ))}
        {product?.map((item) => (
          <meta
            key={item.id}
            property="og:image"
            content={item?.productCategory?.image}
          />
        ))}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={addProductJsonLd()}
          key="product-jsonld"
        />
      </Head>

      <div className="bg-light-pink pt-16 pb-16 ">
        <Title className="mb-5">sản phẩm nổi bật</Title>
        <div className="px-14 my-10">
          <Slider {...settings}>
            {product?.length > 0 &&
              product?.map((item) => {
                return (
                  <div key={item?.id}>
                    <ItemSlide
                      link={`/san-pham/${item?.productSlug}`}
                      image={item?.productImage[0]?.image || ""}
                      name={item?.name}
                      price={Number(item?.productDetail[0]?.price)}
                    ></ItemSlide>
                  </div>
                );
              })}
          </Slider>
        </div>
        <Button
          onClick={() => router.push("/san-pham")}
          className="bg-regal-red text-[#fef9f2] p-2 rounded-lg mx-auto block"
        >
          xem thêm
        </Button>
      </div>
      <div className="py-20 ml-20 flex items-center justify-center">
        <div>
          <h3 className="uppercase">học viện đào tạo sheshi</h3>
        </div>
        <iframe
          width="500"
          height="250"
          src="https://www.youtube.com/embed/ke6a2bODRYE"
          title="Học viện đào tạo Meta Group"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowFullScreen
        ></iframe>
      </div>
      <div className="py-20 bg-light-pink"></div>
      <div className="mt-10">
        <div>
          <h2 className="uppercase text-regal-red font-bold text-2xl text-center mb-5">
            sản phẩm mới
          </h2>
          <div className="px-14 my-10">
            <div className="px-14 my-10">
              <Slider {...settings}>
                {productNew?.length > 0 &&
                  productNew?.map((item) => {
                    // console.log('item',item.productSlug)
                    return (
                      <div key={item.id}>
                        <ItemSlide
                          link={`/san-pham/${item?.productSlug}`}
                          image={item?.productImage[0]?.image || ""}
                          name={item?.name}
                          price={Number(item?.productDetail[0]?.price || 0)}
                        ></ItemSlide>
                      </div>
                    );
                  })}
              </Slider>
            </div>
          </div>
          <Button
            onClick={() => router.push("/san-pham")}
            className="bg-regal-red text-light-pink p-2 rounded-lg mx-auto block"
          >
            xem thêm
          </Button>
        </div>
        <div className="mt-20">
          <h2 className="uppercase text-regal-red font-bold text-2xl text-center mb-5">
            cảm nhận khách hàng
          </h2>
          <p className="text-center w-[800px] mx-auto">
            Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
            SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn về sản
            phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm sản phẩm.
          </p>
        </div>

        <Swiper
          modules={[Navigation, Pagination, Scrollbar, A11y, EffectCube]}
          spaceBetween={50}
          slidesPerView={1}
          navigation
          onSlideChange={() => console.log("slide change")}
          onSwiper={(swiper) => console.log(swiper)}
        >
          <SwiperSlide className="mt-14 flex items-center">
            <div className="flex items-center justify-between p-10">
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
              <CartSlide
                src={`${feed1?.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
            </div>
          </SwiperSlide>
          <SwiperSlide className="mt-14 flex items-center">
            <div className="flex items-center justify-between p-10">
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
            </div>
          </SwiperSlide>
          <SwiperSlide className="mt-14 flex items-center">
            <div className="w-full flex items-center justify-between p-10">
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
              <CartSlide
                src={`${feed1.src}`}
                width={50}
                height={50}
                name="mrs.m lê thúy"
                comment="Cảm nhận của khách hàng đã sử dụng sản phẩm và dịch vụ mỹ phẩm
                  SHESHI. Bạn thì sao? Hãy cho chúng tôi biết cảm nhận của bạn
                  về sản phẩm hoặc đến với chúng tôi để cảm nhận và trải nghiệm
                  sản phẩm."
                face="facebook"
              ></CartSlide>
            </div>
          </SwiperSlide>
          ...
        </Swiper>
      </div>
    </>
  );
}
// const OUTSTANDING_PRODUCTS = 1;
// export async function getStaticProps() {
//   const params = {
//     size: 5,
//     outstanding: OUTSTANDING_PRODUCTS,
//     getMainImage: true,
//     status: GLOBAL_STATUS.ACTIVE,
//   };

//   const data = await axios.get("http://0.0.0.0:3001/api/product", { params });
//   const product = data.data;
//   return {
//     props: { product },
//   };
// }

// export async function getServerSideProps() {
//   const contents = await axios.get(
//     `http://0.0.0.0:3001/api/config-page/content-page?pageCode=${CONTENT_PAGE.SCHOOL_PAGE_OVERVIEW}`
//   );
//   const data = contents.data;
//   const images = await axios.get(
//     "http://0.0.0.0:3001/api/config-page/slide-page",);
//     const slide = {data, images}
//   return {
//     props: { slide },
//   };
// }
